# Form implementation generated from reading ui file 'ui/preview.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1300, 800)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttons_frame = QtWidgets.QFrame(parent=Dialog)
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.copy = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.copy.setObjectName("copy")
        self.horizontalLayout.addWidget(self.copy)
        self.close = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.verticalLayout.addWidget(self.buttons_frame)
        self.preview_box = QtWidgets.QTextEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.preview_box.setFont(font)
        self.preview_box.setReadOnly(True)
        self.preview_box.setObjectName("preview_box")
        self.verticalLayout.addWidget(self.preview_box)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.copy.setText(_translate("Dialog", "󰆏"))
        self.close.setText(_translate("Dialog", "󱎘"))
