# Form implementation generated from reading ui file '../ui/fileoperation.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(620, 143)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.file_password = QtWidgets.QLineEdit(parent=Form)
        self.file_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.file_password.setObjectName("file_password")
        self.horizontalLayout_2.addWidget(self.file_password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backup = QtWidgets.QPushButton(parent=Form)
        self.backup.setObjectName("backup")
        self.horizontalLayout.addWidget(self.backup)
        self.restore = QtWidgets.QPushButton(parent=Form)
        self.restore.setObjectName("restore")
        self.horizontalLayout.addWidget(self.restore)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.file_status = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.file_status.setFont(font)
        self.file_status.setObjectName("file_status")
        self.verticalLayout.addWidget(self.file_status)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.confirm = QtWidgets.QPushButton(parent=self.widget)
        self.confirm.setObjectName("confirm")
        self.horizontalLayout_4.addWidget(self.confirm)
        spacerItem1 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Backup/Restore Password"))
        self.backup.setText(_translate("Form", "Backup"))
        self.restore.setText(_translate("Form", "Restore"))
        self.file_status.setText(_translate("Form", "Choose an option..."))
        self.confirm.setText(_translate("Form", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
