# Form implementation generated from reading ui file '../../ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(334, 143)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.password = QtWidgets.QLineEdit(parent=Form)
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.otp = QtWidgets.QLineEdit(parent=Form)
        self.otp.setObjectName("otp")
        self.horizontalLayout_2.addWidget(self.otp)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.keyfile = QtWidgets.QPushButton(parent=Form)
        self.keyfile.setObjectName("keyfile")
        self.verticalLayout.addWidget(self.keyfile)
        self.login_button = QtWidgets.QPushButton(parent=Form)
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PASSWORD"))
        self.label_2.setText(_translate("Form", "OTP             "))
        self.keyfile.setText(_translate("Form", "Choose Keyfile"))
        self.login_button.setText(_translate("Form", "LOGIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
