# Form implementation generated from reading ui file 'ui/login_register.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 150)
        self.main_widget = QtWidgets.QWidget(parent=MainWindow)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.f4 = QtWidgets.QFrame(parent=self.main_widget)
        self.f4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.f4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.f4.setObjectName("f4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.f4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.f1 = QtWidgets.QFrame(parent=self.f4)
        self.f1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.f1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.f1.setObjectName("f1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.f1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username_label = QtWidgets.QLabel(parent=self.f1)
        self.username_label.setObjectName("username_label")
        self.horizontalLayout.addWidget(self.username_label)
        self.username_input = QtWidgets.QLineEdit(parent=self.f1)
        self.username_input.setObjectName("username_input")
        self.horizontalLayout.addWidget(self.username_input)
        self.verticalLayout.addWidget(self.f1)
        self.f2 = QtWidgets.QFrame(parent=self.f4)
        self.f2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.f2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.f2.setObjectName("f2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.f2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password_label = QtWidgets.QLabel(parent=self.f2)
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_2.addWidget(self.password_label)
        self.password_input = QtWidgets.QLineEdit(parent=self.f2)
        self.password_input.setEnabled(True)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_input.setObjectName("password_input")
        self.horizontalLayout_2.addWidget(self.password_input)
        self.verticalLayout.addWidget(self.f2)
        spacerItem = QtWidgets.QSpacerItem(20, 161, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.f3 = QtWidgets.QFrame(parent=self.f4)
        self.f3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.f3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.f3.setObjectName("f3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.f3)
        self.horizontalLayout_3.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.register_button = QtWidgets.QPushButton(parent=self.f3)
        self.register_button.setObjectName("register_button")
        self.horizontalLayout_3.addWidget(self.register_button)
        self.login_button = QtWidgets.QPushButton(parent=self.f3)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_3.addWidget(self.login_button)
        self.verticalLayout.addWidget(self.f3)
        self.verticalLayout_2.addWidget(self.f4)
        MainWindow.setCentralWidget(self.main_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.password_label.setText(_translate("MainWindow", "Password "))
        self.register_button.setText(_translate("MainWindow", "Register"))
        self.login_button.setText(_translate("MainWindow", "Login"))
